### ISSUE TITLE
Feature Request: Subtasks

### ISSUE THREAD

**Issue by NickVCBS** [manojuppala/tasklist-cli#5]
Hello there. 

First off I want to say I love the simplicity of this! It's just what I need for a daily driver. I stumbled upon your post on [reddit](https://www.reddit.com/r/commandline/comments/st16gd/i_made_the_best_command_line_todolist_application/) earlier today looking for a small tasking tool for daily work. 

One addition I think would be an awesome feature to add would be a way to either group tasks or label them into a specific category. 

For example, if I was working on _Project A_ and wanted to write all the executable tasks for that project, the only way I can accomplish that currently is with some sort of flat structure using delimiters (e.g `project-a-task1`, project-a-task2` etc)

I think it'd be a great addition to the CLI tool if feasible

**Comment by manojuppala** [comment]
thanks for the feedback. i am currently working on that feature, will be available on the next release which will be out this weekend.

**Comment by manojuppala** [comment]
@NickVCBS  projects and sub-tasks are now available in **v1.2.0**
